# Generated by Django 4.0.2 on 2022-03-23 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0004_alter_employee_emp_id_alter_employee_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='emp_id',
            field=models.CharField(default='emp386', max_length=70),
        ),
        migrations.AlterField(
            model_name='employee',
            name='thumb',
            field=models.ImageField(blank=True, max_length=70, upload_to='media/%Y/%m/%d/'),
        ),
    ]
